services:
  jaeger:
    image: jaegertracing/all-in-one:1.41
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
    networks: [obs]

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "14318:4318"   # browser -> collector
    depends_on:
      - jaeger
    networks: [obs]

  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_DATABASE: productdb
      MYSQL_USER: productuser
      MYSQL_PASSWORD: productpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks: [ obs ]

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-obs-backend
    environment:
      - OTEL_SERVICE_NAME=product-obs-backend
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=http/protobuf
      - OTEL_PROPAGATORS=tracecontext,baggage
      - OTEL_METRICS_EXPORTER=none
      - OTEL_LOGS_EXPORTER=none
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector
      - mysql
    networks: [ obs ]


  frontend:
    build: ../product-obs-frontend
    container_name: product-obs-frontend
    ports:
      - '4200:4200'
    depends_on:
      - backend
    networks: [ obs ]


networks:
  obs: {}

volumes:
  mysql_data: {}
